version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres_imobiliaria
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=teste
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
    volumes:
      - dados_postgres:/var/lib/postgresql/data

  # Serviço do Zookeeper (dependência do Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  # Serviço do Kafka
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

volumes:
  dados_postgres: